FROM node:22-slim
RUN corepack enable && corepack prepare pnpm@latest --activate
WORKDIR /app

COPY pnpm-lock.yaml pnpm-workspace.yaml package.json ./

COPY apps/*/package.json ./apps/

COPY packages/*/package.json ./packages/

RUN pnpm install

CMD ["pnpm", "turbo", "run", "dev"]
